name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Package Installation
        run: Rscript -e 'install.packages(c("tidyverse" ,"devtools", "dplyr", "stringr", "here", "lubridate", "janitor", "piggyback"))'
      - name: worldfootballR Package Installation
        run: Rscript -e 'devtools::install_github("JaseZiv/worldfootballR")'
      - name: Run
        run: Rscript -e 'source(file.path("tests", "test.R"), echo = TRUE)'
