name: spoof_test

on:
  push:
    branches: [ "spoof_headers_gha" ]
  pull_request:
    branches: [ "spoof_headers_gha" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macOS-latest
    # retrieve token
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Package Installation
        run: Rscript -e 'install.packages(c("rstudioapi", "utils", "httr", "xml2", "rvest"))'
      - name: Run set agent
        run: Rscript -e 'source("test.R", echo = TRUE)'
